// Generated from catalog/redgifs_niches_of_references_catalog.xlsx.
// Runtime never downloads or manually refreshes this catalog.

export interface ReferenceCatalogEntry {
  id: number;
  slug: string;
  title: string;
  category: string;
  description: string;
}

export interface ReferenceCategory {
  key: string;
  title: string;
  count: number;
}

export const REFERENCE_CATALOG_VERSION = "abf4c06a0ce79a66";
export const REFERENCE_CATALOG_COUNT = 473;

export const REFERENCE_CATEGORIES: readonly ReferenceCategory[] = Object.freeze([
  {"key":"action","title":"Действия и сцены","count":214},
  {"key":"appearance","title":"Типаж и внешность","count":144},
  {"key":"outfit","title":"Образы и одежда","count":30},
  {"key":"camera","title":"Камера, позы и ракурсы","count":30},
  {"key":"roleplay","title":"Сценарии и roleplay","count":25},
  {"key":"performance","title":"Подача и performance","count":13},
  {"key":"cosplay","title":"Cosplay и образы","count":13},
  {"key":"location","title":"Локации и ситуации","count":4},
]);

export const REFERENCE_CATALOG: readonly ReferenceCatalogEntry[] = Object.freeze([
  {"id":1,"slug":"2-1","title":"2dicks1chick","category":"action","description":"Два мужчины и одна женщина; групповая партнёрская сцена. Официальное описание RedGIFs отсутствует."},
  {"id":2,"slug":"3some-with-tgirls","title":"3some With Tgirls","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «3some With Tgirls»."},
  {"id":3,"slug":"3-somes","title":"3Somes","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «3Somes»."},
  {"id":4,"slug":"acoustic-backshots","title":"Acoustic Backshots","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Acoustic Backshots»."},
  {"id":5,"slug":"adorable-porn","title":"Adorable Porn","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Adorable Porn»."},
  {"id":6,"slug":"african-queen","title":"African Queens","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «African Queens»."},
  {"id":7,"slug":"after-suck","title":"After Suck","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «After Suck»."},
  {"id":8,"slug":"age-gap","title":"Age Gap","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Age Gap»."},
  {"id":9,"slug":"ahegao-face","title":"AhegaoFace","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «AhegaoFace»."},
  {"id":10,"slug":"all-about-gags","title":"All About Gags","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «All About Gags»."},
  {"id":11,"slug":"alt-girls","title":"Alt Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Alt Girls»."},
  {"id":12,"slug":"alt-girl-squirting","title":"Alt Girls Squirting","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Alt Girls Squirting»."},
  {"id":13,"slug":"amateur-girls","title":"Amateur Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Amateur Girls»."},
  {"id":14,"slug":"amateur-interracial","title":"Amateur Interracial","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Amateur Interracial»."},
  {"id":15,"slug":"amateur-model","title":"Amateur Models","category":"appearance","description":"Контент любительских моделей. Официальное описание RedGIFs отсутствует."},
  {"id":16,"slug":"amateur-wife","title":"Amateur Wives","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Amateur Wives»."},
  {"id":17,"slug":"amputee-obsession","title":"Amputee Obsession","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Amputee Obsession»."},
  {"id":18,"slug":"amxf","title":"AMXF (Asian Male Any Female)","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «AMXF (Asian Male Any Female)»."},
  {"id":19,"slug":"anal-creampie","title":"Anal Creampie","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Anal Creampie»."},
  {"id":20,"slug":"anal-dildo","title":"Anal Dildo","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Anal Dildo»."},
  {"id":21,"slug":"anal-masturbation-instruction","title":"Anal JOI","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Anal JOI»."},
  {"id":22,"slug":"anal-orgasms","title":"Anal Orgasms","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Anal Orgasms»."},
  {"id":23,"slug":"anal-queens","title":"Anal Queens","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Anal Queens»."},
  {"id":24,"slug":"anal-sex","title":"Anal Sex","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Anal Sex»."},
  {"id":25,"slug":"anal-squirting","title":"Anal Squirting","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Anal Squirting»."},
  {"id":26,"slug":"ankle-socks","title":"Ankle Socks","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Ankle Socks»."},
  {"id":27,"slug":"arab-hotwife","title":"Arab Hotwife","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Arab Hotwife»."},
  {"id":28,"slug":"arizona-girls","title":"Arizona Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Arizona Girls»."},
  {"id":29,"slug":"armpits","title":"Armpits","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Armpits»."},
  {"id":30,"slug":"asian-anal","title":"Asian Anal","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Asian Anal»."},
  {"id":31,"slug":"asian-creampies","title":"Asian Creampies","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Asian Creampies»."},
  {"id":32,"slug":"asianfeet","title":"Asian Feet","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Asian Feet»."},
  {"id":33,"slug":"asian-milf","title":"Asian MILF","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Asian MILF»."},
  {"id":34,"slug":"asian-pussy","title":"Asian Pussy","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Asian Pussy»."},
  {"id":35,"slug":"asian-sex","title":"Asian sex","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Asian sex»."},
  {"id":36,"slug":"asian-with-bbc","title":"Asians with BBC!","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Asians with BBC!»."},
  {"id":37,"slug":"ass-clap","title":"Ass Clap","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Ass Clap»."},
  {"id":38,"slug":"ass-licking","title":"Ass Licking","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Ass Licking»."},
  {"id":39,"slug":"ass-spread-and-feet","title":"Ass Spread & Feet","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Ass Spread & Feet»."},
  {"id":40,"slug":"ass-worship","title":"Ass Worship","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Ass Worship»."},
  {"id":41,"slug":"ass-holes-and-pussy","title":"Asshole & Pussy","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Asshole & Pussy»."},
  {"id":42,"slug":"asshole-behind-thong","title":"Asshole Behind Thong","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Asshole Behind Thong»."},
  {"id":43,"slug":"assjob","title":"Assjob","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Assjob»."},
  {"id":44,"slug":"at-work","title":"At Work","category":"location","description":"Съёмочная ситуация или локационный концепт «At Work»."},
  {"id":45,"slug":"audio","title":"Audio","category":"performance","description":"Формат подачи, речь/звук или performance-приём «Audio»."},
  {"id":46,"slug":"audio-erotica","title":"Audio Erotica","category":"performance","description":"Формат подачи, речь/звук или performance-приём «Audio Erotica»."},
  {"id":47,"slug":"babysitter","title":"Babysitters","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Babysitters»."},
  {"id":48,"slug":"back-arched","title":"Back Arched","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Back Arched»."},
  {"id":49,"slug":"backshots-from-bbc","title":"Backshots From BBC","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Backshots From BBC»."},
  {"id":50,"slug":"bad-dragon-toy-lovers","title":"Bad Dragon Toy Lovers","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Bad Dragon Toy Lovers»."},
  {"id":51,"slug":"ball-worship","title":"Ball Worship","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Ball Worship»."},
  {"id":52,"slug":"bare-face","title":"Bare Face","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Bare Face»."},
  {"id":53,"slug":"bbc-cuckold","title":"BBC Cuckold","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «BBC Cuckold»."},
  {"id":54,"slug":"bbc-dildos","title":"BBC Dildos","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «BBC Dildos»."},
  {"id":55,"slug":"bbc-milf","title":"BBC MILFs","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «BBC MILFs»."},
  {"id":56,"slug":"bbw-goth-babes","title":"BBW Goth Babes","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «BBW Goth Babes»."},
  {"id":57,"slug":"beat-it-up","title":"Beat It Up","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Beat It Up»."},
  {"id":58,"slug":"dwarf-and-midget","title":"Beautiful Midgets","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Beautiful Midgets»."},
  {"id":59,"slug":"beautiful-porn","title":"Beautiful Porn","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Beautiful Porn»."},
  {"id":60,"slug":"beautiful-trans-dick","title":"Beautiful Trans Dick","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Beautiful Trans Dick»."},
  {"id":61,"slug":"beautiful-woman-with-beautiful-pussy","title":"Beautiful Women With Beautiful Pussy","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Beautiful Women With Beautiful Pussy»."},
  {"id":62,"slug":"begging-for-cum","title":"Begging For Cum","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Begging For Cum»."},
  {"id":63,"slug":"being-ignored","title":"Being Ignored","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Being Ignored»."},
  {"id":64,"slug":"benevolent-findom","title":"Benevolent Findom","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Benevolent Findom»."},
  {"id":65,"slug":"r-betacuck","title":"Betacuck","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Betacuck»."},
  {"id":66,"slug":"between-2-cocks","title":"Between 2 Cocks","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Between 2 Cocks»."},
  {"id":67,"slug":"bi-kinky","title":"Bi Kinky","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Bi Kinky»."},
  {"id":68,"slug":"bi-fucklick","title":"Bi-Fucklick","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Bi-Fucklick»."},
  {"id":69,"slug":"big-areolas","title":"Big Areolas","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Big Areolas»."},
  {"id":70,"slug":"big-ass-riding","title":"Big Ass Riding","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Big Ass Riding»."},
  {"id":71,"slug":"big-asses","title":"Big Asses","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Big Asses»."},
  {"id":72,"slug":"big-bellies","title":"Big Bellies","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Big Bellies»."},
  {"id":73,"slug":"big-clit","title":"Big Clits","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Big Clits»."},
  {"id":74,"slug":"big-nipples","title":"Big Nipples","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Big Nipples»."},
  {"id":75,"slug":"bigtits","title":"Big Tits","category":"appearance","description":"Женский типаж с большой грудью. Официальное описание RedGIFs отсутствует."},
  {"id":76,"slug":"bikinis","title":"Bikinis","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Bikinis»."},
  {"id":77,"slug":"bimbos","title":"Bimbos","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Bimbos»."},
  {"id":78,"slug":"bisexual","title":"Bisexual","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Bisexual»."},
  {"id":79,"slug":"bitchsuits","title":"Bitchsuits","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Bitchsuits»."},
  {"id":80,"slug":"black-male-white-female-bmwf","title":"Black Male White Female (BMWF)","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Black Male White Female (BMWF)»."},
  {"id":81,"slug":"black-men-white-women-kissing","title":"Black Men & White Women Kissing","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Black Men & White Women Kissing»."},
  {"id":82,"slug":"black-owned-white-wives","title":"Black Owned White Wives","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Black Owned White Wives»."},
  {"id":83,"slug":"black-underwear","title":"Black Underwear","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Black Underwear»."},
  {"id":84,"slug":"blacklight","title":"Blacklight","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Blacklight»."},
  {"id":85,"slug":"blonde-pawg","title":"Blonde Pawgs","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Blonde Pawgs»."},
  {"id":86,"slug":"blonde-bbc-unseen-male-face","title":"Blonde+BBC Unseen Male Face","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Blonde+BBC Unseen Male Face»."},
  {"id":87,"slug":"blowbang-bukkake","title":"Blowbang Bukkake","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Blowbang Bukkake»."},
  {"id":88,"slug":"blowjob-sluts","title":"Blowjob Sluts","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Blowjob Sluts»."},
  {"id":89,"slug":"blowjobs","title":"Blowjobs","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Blowjobs»."},
  {"id":90,"slug":"bmxf","title":"BMxF (Black Male x Female)","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «BMxF (Black Male x Female)»."},
  {"id":91,"slug":"bondage-sluts","title":"Bondage Sluts","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Bondage Sluts»."},
  {"id":92,"slug":"booty-shorts","title":"Booty Shorts","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Booty Shorts»."},
  {"id":93,"slug":"bouncing-boobs","title":"Bouncing Boobs","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Bouncing Boobs»."},
  {"id":94,"slug":"bound-fucked","title":"Bound & Fucked","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Bound & Fucked»."},
  {"id":95,"slug":"breast-envy","title":"Breast Envy","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Breast Envy»."},
  {"id":96,"slug":"breeding","title":"Breeding","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Breeding»."},
  {"id":97,"slug":"brides","title":"Brides","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Brides»."},
  {"id":98,"slug":"british-babes","title":"British Babes","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «British Babes»."},
  {"id":99,"slug":"brunette-pawg-s","title":"Brunette PAWGs","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Brunette PAWGs»."},
  {"id":100,"slug":"bubble-butt","title":"Bubble Butt","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Bubble Butt»."},
  {"id":101,"slug":"bubbly-creampies","title":"Bubbly Creampies","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Bubbly Creampies»."},
  {"id":102,"slug":"bush-lover","title":"Bush Lovers","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Bush Lovers»."},
  {"id":103,"slug":"busty-asians","title":"Busty Asians","category":"appearance","description":"Азиатские модели с большой грудью. Официальное описание RedGIFs отсутствует."},
  {"id":104,"slug":"busty-petite","title":"Busty Petite","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Busty Petite»."},
  {"id":105,"slug":"busty-sluts","title":"Busty Sluts","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Busty Sluts»."},
  {"id":106,"slug":"calvin-klein-girls","title":"Calvin Klein Girls","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Calvin Klein Girls»."},
  {"id":107,"slug":"cam-girls","title":"Cam Girls","category":"performance","description":"Формат подачи, речь/звук или performance-приём «Cam Girls»."},
  {"id":108,"slug":"camel-toes","title":"Camel Toes","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Camel Toes»."},
  {"id":109,"slug":"yvrcanada","title":"Canada","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Canada»."},
  {"id":110,"slug":"cat-girls","title":"Cat Girls","category":"cosplay","description":"Воспроизводимый cosplay/образ или тематический roleplay «Cat Girls»."},
  {"id":111,"slug":"caught-porn","title":"Caught Porn","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Caught Porn»."},
  {"id":112,"slug":"cheating","title":"Cheating","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Cheating»."},
  {"id":113,"slug":"cheating-wife","title":"Cheating Wife","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Cheating Wife»."},
  {"id":114,"slug":"chubby-girls","title":"Chubby Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Chubby Girls»."},
  {"id":115,"slug":"cis-women-fucking-trans-women","title":"Cis Women Fucking Trans Women","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Cis Women Fucking Trans Women»."},
  {"id":116,"slug":"clapping-boobs","title":"Clapping Boobs","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Clapping Boobs»."},
  {"id":117,"slug":"clit-suckers","title":"Clit Suckers","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Clit Suckers»."},
  {"id":118,"slug":"close-up","title":"Close Up","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Close Up»."},
  {"id":119,"slug":"close-up-penetration","title":"Close Up Penetration","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Close Up Penetration»."},
  {"id":120,"slug":"close-up-ass","title":"Close-Up Ass","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Close-Up Ass»."},
  {"id":121,"slug":"clothed-masturbating","title":"Clothed Masturbating","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Clothed Masturbating»."},
  {"id":122,"slug":"clothed-twerking","title":"Clothed Twerking","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Clothed Twerking»."},
  {"id":123,"slug":"clothing-fetish","title":"Clothing Fetish","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Clothing Fetish»."},
  {"id":124,"slug":"clown-girls","title":"Clown Girls","category":"cosplay","description":"Воспроизводимый cosplay/образ или тематический roleplay «Clown Girls»."},
  {"id":125,"slug":"cock-head-worship","title":"Cock Head Worship","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cock Head Worship»."},
  {"id":126,"slug":"cock-kisses","title":"Cock Kisses","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cock Kisses»."},
  {"id":127,"slug":"cock-too-big","title":"Cock Too Big","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cock Too Big»."},
  {"id":128,"slug":"cock-pedal-footjobs-shoejobs","title":"Cock-Pedal Footjobs","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cock-Pedal Footjobs»."},
  {"id":129,"slug":"college-sluts","title":"College Sluts","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «College Sluts»."},
  {"id":130,"slug":"country-girls","title":"Country Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Country Girls»."},
  {"id":131,"slug":"covered-in-cum","title":"Covered in Cum","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Covered in Cum»."},
  {"id":132,"slug":"cowgirl-pov","title":"Cowgirl POV","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Cowgirl POV»."},
  {"id":133,"slug":"creampie-eating","title":"Creampie Eating","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Creampie Eating»."},
  {"id":134,"slug":"creampies","title":"Creampies","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Creampies»."},
  {"id":135,"slug":"cuck-queaning","title":"Cuck Queaning","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Cuck Queaning»."},
  {"id":136,"slug":"cucked","title":"Cucked","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Cucked»."},
  {"id":137,"slug":"cum-announcement","title":"Cum Announcement","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cum Announcement»."},
  {"id":138,"slug":"cum-assistants","title":"Cum Assistants","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cum Assistants»."},
  {"id":139,"slug":"cum-coaxing","title":"Cum Coaxing","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cum Coaxing»."},
  {"id":140,"slug":"cum-eating-instructions","title":"Cum Eating Instructions","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cum Eating Instructions»."},
  {"id":141,"slug":"cum-haters","title":"Cum Haters","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cum Haters»."},
  {"id":142,"slug":"cum-kissing","title":"Cum Kissing","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cum Kissing»."},
  {"id":143,"slug":"cum-lover","title":"Cum lovers","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cum lovers»."},
  {"id":144,"slug":"cum-on-armpit","title":"Cum on Armpit","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Cum on Armpit»."},
  {"id":145,"slug":"cum-on-boobs","title":"Cum On Boobs","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cum On Boobs»."},
  {"id":146,"slug":"cum-swallowing-sluts","title":"Cum Swallowing Sluts","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cum Swallowing Sluts»."},
  {"id":147,"slug":"cumkiss","title":"Cumkiss","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cumkiss»."},
  {"id":148,"slug":"cumshot-in-mouth-only","title":"Cumshot In Mouth","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cumshot In Mouth»."},
  {"id":149,"slug":"cumslut","title":"Cumslut","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cumslut»."},
  {"id":150,"slug":"curvy-chicks","title":"Curvy Chicks","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Curvy Chicks»."},
  {"id":151,"slug":"cute-little-butts","title":"Cute Butts","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Cute Butts»."},
  {"id":152,"slug":"cute-trans","title":"Cute Trans","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Cute Trans»."},
  {"id":153,"slug":"dancing","title":"Dancing","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Dancing»."},
  {"id":154,"slug":"dick-sucking-lips","title":"Dick Sucking Lips","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Dick Sucking Lips»."},
  {"id":155,"slug":"dildo-cuckold","title":"Dildo Cuckold","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Dildo Cuckold»."},
  {"id":156,"slug":"dinomask-porn","title":"Dinomask Porn","category":"cosplay","description":"Воспроизводимый cosplay/образ или тематический roleplay «Dinomask Porn»."},
  {"id":157,"slug":"dirty-panties","title":"Dirty Panties","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Dirty Panties»."},
  {"id":158,"slug":"dirty-socks","title":"Dirty Socks","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Dirty Socks»."},
  {"id":159,"slug":"dirty-talk","title":"Dirty Talk","category":"performance","description":"Формат подачи, речь/звук или performance-приём «Dirty Talk»."},
  {"id":160,"slug":"disability-and-sex","title":"Disability and Sex","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Disability and Sex»."},
  {"id":161,"slug":"double-assjob","title":"Double Assjob","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Double Assjob»."},
  {"id":162,"slug":"double-barrel-blowjobs","title":"Double Barrel Blowjobs","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Double Barrel Blowjobs»."},
  {"id":163,"slug":"double-penetration","title":"Double Penetration","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Double Penetration»."},
  {"id":164,"slug":"dripping-pussy","title":"Dripping Pussy","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Dripping Pussy»."},
  {"id":165,"slug":"drool-spit","title":"Drool/Spit","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Drool/Spit»."},
  {"id":166,"slug":"dual-tittyfuck","title":"Dual Tittyfuck","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Dual Tittyfuck»."},
  {"id":167,"slug":"dutch","title":"Dutch","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Dutch»."},
  {"id":168,"slug":"e-girls","title":"E-Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «E-Girls»."},
  {"id":169,"slug":"ebony-ass","title":"Ebony Ass","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Ebony Ass»."},
  {"id":170,"slug":"ebony-footjobs","title":"Ebony Footjobs","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Ebony Footjobs»."},
  {"id":171,"slug":"ebony-girls","title":"Ebony Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Ebony Girls»."},
  {"id":172,"slug":"ebony-grip","title":"Ebony Grip","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Ebony Grip»."},
  {"id":173,"slug":"ebony-titties","title":"Ebony Titties","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Ebony Titties»."},
  {"id":174,"slug":"edging","title":"Edging","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Edging»."},
  {"id":175,"slug":"elf-girls","title":"Elf Girls","category":"cosplay","description":"Воспроизводимый cosplay/образ или тематический roleplay «Elf Girls»."},
  {"id":176,"slug":"embarrassed-naked-females","title":"Embarrassed Naked Females","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Embarrassed Naked Females»."},
  {"id":177,"slug":"engorged-veiny-breasts","title":"Engorged Veiny Breasts","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Engorged Veiny Breasts»."},
  {"id":178,"slug":"long-nipples","title":"Eraser Nipples","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Eraser Nipples»."},
  {"id":179,"slug":"european-babes","title":"European Babes","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «European Babes»."},
  {"id":180,"slug":"eye-contact-with-the-camera","title":"Eye Contact With The Camera","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Eye Contact With The Camera»."},
  {"id":181,"slug":"eye-rolling-orgasms","title":"Eye Rolling Orgasms","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Eye Rolling Orgasms»."},
  {"id":182,"slug":"eyes-on-camera-kissing","title":"Eyes On Camera Kissing","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Eyes On Camera Kissing»."},
  {"id":183,"slug":"face-fucking","title":"Face Fucking","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Face Fucking»."},
  {"id":184,"slug":"face-riding","title":"Face Riding","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Face Riding»."},
  {"id":185,"slug":"face-sit","title":"FaceSitPOV","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «FaceSitPOV»."},
  {"id":186,"slug":"horny-facial-expressions","title":"Facial Expressions","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Facial Expressions»."},
  {"id":187,"slug":"facials","title":"Facials","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Facials»."},
  {"id":188,"slug":"facing-camera","title":"Facing Camera","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Facing Camera»."},
  {"id":189,"slug":"fair-haired","title":"Fair-Haired","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Fair-Haired»."},
  {"id":190,"slug":"fake-boobs","title":"Fake Boobs","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Fake Boobs»."},
  {"id":191,"slug":"fat-ass-anal","title":"Fat Ass Anal","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Fat Ass Anal»."},
  {"id":192,"slug":"fat-pussy","title":"Fat Pussy","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Fat Pussy»."},
  {"id":193,"slug":"feet","title":"Feet","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Feet»."},
  {"id":194,"slug":"feet-up-trans","title":"Feet Up Trans","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Feet Up Trans»."},
  {"id":195,"slug":"feet-view","title":"Feet View","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Feet View»."},
  {"id":196,"slug":"female-anal-masturbation","title":"Female Anal Masturbation","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Female Anal Masturbation»."},
  {"id":197,"slug":"female-domination-pov","title":"Female Domination POV","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Female Domination POV»."},
  {"id":198,"slug":"female-masturbation","title":"Female Masturbation","category":"action","description":"Женская мастурбация. Официальное описание RedGIFs отсутствует."},
  {"id":199,"slug":"female-orgasms","title":"Female Orgasms","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Female Orgasms»."},
  {"id":200,"slug":"femdom-chastity","title":"FemDom Chastity","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «FemDom Chastity»."},
  {"id":201,"slug":"femdom-cum-feeding","title":"Femdom Cum Feeding","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Femdom Cum Feeding»."},
  {"id":202,"slug":"femdom-handjobs","title":"Femdom Handjobs","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Femdom Handjobs»."},
  {"id":203,"slug":"femdom-pov","title":"FemDom POV","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «FemDom POV»."},
  {"id":204,"slug":"sissy-training","title":"FemDom Sissy Training","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «FemDom Sissy Training»."},
  {"id":205,"slug":"feminizing-hypnosis","title":"Feminizing Hypnosis","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Feminizing Hypnosis»."},
  {"id":206,"slug":"femme-fatales","title":"Femme Fatales","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Femme Fatales»."},
  {"id":207,"slug":"findom","title":"Findom","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Findom»."},
  {"id":208,"slug":"fit-girls","title":"Fit Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Fit Girls»."},
  {"id":209,"slug":"fitness-girls","title":"Fitness Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Fitness Girls»."},
  {"id":210,"slug":"flexible-fucking","title":"Flexible Fucking","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Flexible Fucking»."},
  {"id":211,"slug":"foot-queen","title":"Foot Queen","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Foot Queen»."},
  {"id":212,"slug":"fucking-machines","title":"Fucking Machines","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Fucking Machines»."},
  {"id":213,"slug":"full-back-panties","title":"Full Back Panties","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Full Back Panties»."},
  {"id":214,"slug":"full-bush-mature-milf","title":"Full Bush Mature MILFs","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Full Bush Mature MILFs»."},
  {"id":215,"slug":"fun-size-asians","title":"Fun Sized Asians","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Fun Sized Asians»."},
  {"id":216,"slug":"funny-porn","title":"Funny Porn","category":"performance","description":"Формат подачи, речь/звук или performance-приём «Funny Porn»."},
  {"id":217,"slug":"fursuit-sex","title":"Fursuit Sex","category":"cosplay","description":"Воспроизводимый cosplay/образ или тематический roleplay «Fursuit Sex»."},
  {"id":218,"slug":"gagging","title":"Gagging","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Gagging»."},
  {"id":219,"slug":"gangbang-creampie","title":"Gangbang Creampie","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Gangbang Creampie»."},
  {"id":220,"slug":"ghoul","title":"Ghoul","category":"cosplay","description":"Воспроизводимый cosplay/образ или тематический roleplay «Ghoul»."},
  {"id":221,"slug":"girl-on-big-dick-unseen-male-face","title":"Girl On Big Dick + Unseen Male Face","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Girl On Big Dick + Unseen Male Face»."},
  {"id":222,"slug":"girl-on-girl","title":"Girl on Girl","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Girl on Girl»."},
  {"id":223,"slug":"girlfriend-experience","title":"Girlfriend Experience","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Girlfriend Experience»."},
  {"id":224,"slug":"girls-and-cum-only","title":"Girls And Cum ONLY","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Girls And Cum ONLY»."},
  {"id":225,"slug":"girls-finishing-the-job","title":"Girls Finishing The Job","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Girls Finishing The Job»."},
  {"id":226,"slug":"girls-fisting-guys","title":"Girls Fisting Guys","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Girls Fisting Guys»."},
  {"id":227,"slug":"girls-in-yoga-pants","title":"Girls In Yoga Pants","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Girls In Yoga Pants»."},
  {"id":228,"slug":"girls-kissing","title":"Girls Kissing","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Girls Kissing»."},
  {"id":229,"slug":"group-of-nude-girls","title":"Girls Playing","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Girls Playing»."},
  {"id":230,"slug":"girls-showering","title":"Girls Showering","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Girls Showering»."},
  {"id":231,"slug":"girls-with-glasses","title":"Girls With Glasses","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Girls With Glasses»."},
  {"id":232,"slug":"girls-with-neon-hair","title":"Girls With Neon Hair","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Girls With Neon Hair»."},
  {"id":233,"slug":"glass-dildos","title":"Glass Dildos","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Glass Dildos»."},
  {"id":234,"slug":"gloryholes","title":"Gloryholes","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Gloryholes»."},
  {"id":235,"slug":"goddess-worship","title":"Goddess Worship","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Goddess Worship»."},
  {"id":236,"slug":"gonzo-porn","title":"Gonzo Porn","category":"performance","description":"Формат подачи, речь/звук или performance-приём «Gonzo Porn»."},
  {"id":237,"slug":"goon","title":"Goon","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Goon»."},
  {"id":238,"slug":"gooning-and-edging-for-goddess","title":"Gooning & Edging For Goddess","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Gooning & Edging For Goddess»."},
  {"id":239,"slug":"goth-big-ass","title":"Goth Big Ass","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Goth Big Ass»."},
  {"id":240,"slug":"goth-girls","title":"Goth Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Goth Girls»."},
  {"id":241,"slug":"group-fucking","title":"Group Fucking","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Group Fucking»."},
  {"id":242,"slug":"group-sex-parties","title":"Group Sex Parties","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Group Sex Parties»."},
  {"id":243,"slug":"guys-getting-pegged","title":"Guys Getting Pegged","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Guys Getting Pegged»."},
  {"id":244,"slug":"hairy-girls","title":"Hairy Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Hairy Girls»."},
  {"id":245,"slug":"hairy-pussy-queer","title":"Hairy Pussy Queer","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Hairy Pussy Queer»."},
  {"id":246,"slug":"halloween-2023","title":"Halloween","category":"cosplay","description":"Воспроизводимый cosplay/образ или тематический roleplay «Halloween»."},
  {"id":247,"slug":"handjob","title":"Handjobs","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Handjobs»."},
  {"id":248,"slug":"her-hair","title":"Her Hair","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Her Hair»."},
  {"id":249,"slug":"heteroflexible","title":"Heteroflexible","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Heteroflexible»."},
  {"id":250,"slug":"high-heels","title":"High Heels","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «High Heels»."},
  {"id":251,"slug":"homemade","title":"Homemade","category":"performance","description":"Формат подачи, речь/звук или performance-приём «Homemade»."},
  {"id":252,"slug":"horny-cougars","title":"Horny Cougars","category":"appearance","description":"Зрелые женщины / cougar-типаж. Официальное описание RedGIFs отсутствует."},
  {"id":253,"slug":"hot-bbw-moms-who-want-love-too","title":"Hot BBW Moms Who Want Love Too","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Hot BBW Moms Who Want Love Too»."},
  {"id":254,"slug":"hot-girls-with-tattoos","title":"Hot Girls With Tattoos","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Hot Girls With Tattoos»."},
  {"id":255,"slug":"hotwife-lifestyle","title":"Hotwife Lifestyle","category":"roleplay","description":"Hotwife/cuckold-партнёрская динамика. Официальное описание RedGIFs отсутствует."},
  {"id":256,"slug":"hubbys-view","title":"Hubby's View","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Hubby's View»."},
  {"id":257,"slug":"hucow","title":"Hucow","category":"cosplay","description":"Воспроизводимый cosplay/образ или тематический roleplay «Hucow»."},
  {"id":258,"slug":"hypno-play","title":"Hypno Play","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Hypno Play»."},
  {"id":259,"slug":"in-the-car","title":"In The Car","category":"location","description":"Съёмочная ситуация или локационный концепт «In The Car»."},
  {"id":260,"slug":"indian-babes","title":"Indian Babes","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Indian Babes»."},
  {"id":261,"slug":"indian-sluts","title":"Indian Sluts","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Indian Sluts»."},
  {"id":262,"slug":"indonesians","title":"Indonesians","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Indonesians»."},
  {"id":263,"slug":"innie","title":"Innie","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Innie»."},
  {"id":264,"slug":"interracial-submissive-cuckold","title":"Interracial submissive cuckolds","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Interracial submissive cuckolds»."},
  {"id":265,"slug":"japanese-babes","title":"Japanese Babes","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Japanese Babes»."},
  {"id":266,"slug":"jav-japanese-adult-video","title":"JAV (Japanese Adult Video)","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «JAV (Japanese Adult Video)»."},
  {"id":267,"slug":"jav-big-butt","title":"JAV Big Butt","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «JAV Big Butt»."},
  {"id":268,"slug":"jav-moms-lovers","title":"JAV Moms","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «JAV Moms»."},
  {"id":269,"slug":"jerk-off-instructions","title":"Jerk Off Instructions","category":"performance","description":"Формат подачи, речь/звук или performance-приём «Jerk Off Instructions»."},
  {"id":270,"slug":"jiggle-fuck","title":"JiggleFuck","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «JiggleFuck»."},
  {"id":271,"slug":"jilling","title":"Jilling","category":"action","description":"Женская мастурбация (jilling). Официальное описание RedGIFs отсутствует."},
  {"id":272,"slug":"jilling-cumsluts","title":"Jilling Cumsluts","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Jilling Cumsluts»."},
  {"id":273,"slug":"joi","title":"JOI (Jerk Off Instructions)","category":"performance","description":"Формат подачи, речь/звук или performance-приём «JOI (Jerk Off Instructions)»."},
  {"id":274,"slug":"jug-fuckers","title":"Jug Fuckers","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Jug Fuckers»."},
  {"id":275,"slug":"just-boobs","title":"Just Boobs","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Just Boobs»."},
  {"id":276,"slug":"pussy","title":"Just Pussy","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Just Pussy»."},
  {"id":277,"slug":"kerala-babes","title":"Kerala Babes","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Kerala Babes»."},
  {"id":278,"slug":"kiwi-girls","title":"Kiwi Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Kiwi Girls»."},
  {"id":279,"slug":"knotted","title":"Knotted","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Knotted»."},
  {"id":280,"slug":"korean-nsfw","title":"Korean NSFW","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Korean NSFW»."},
  {"id":281,"slug":"lactation","title":"Lactation","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Lactation»."},
  {"id":282,"slug":"ladyboys","title":"Ladyboys","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Ladyboys»."},
  {"id":283,"slug":"latex","title":"Latex","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Latex»."},
  {"id":284,"slug":"latina-creampies","title":"Latina Creampies","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Latina Creampies»."},
  {"id":285,"slug":"latinas","title":"Latinas","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Latinas»."},
  {"id":286,"slug":"leashed-women","title":"Leashed Women","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Leashed Women»."},
  {"id":287,"slug":"leather-skirt","title":"Leather Skirts","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Leather Skirts»."},
  {"id":288,"slug":"legs-from-behind","title":"Legs From Behind","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Legs From Behind»."},
  {"id":289,"slug":"legs-spread","title":"Legs Spread","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Legs Spread»."},
  {"id":290,"slug":"legs-up","title":"Legs Up","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Legs Up»."},
  {"id":291,"slug":"lesbian-breast-worship","title":"Lesbian Breast Worship","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Lesbian Breast Worship»."},
  {"id":292,"slug":"lesbian-spit-kisses","title":"Lesbian Spit Kisses","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Lesbian Spit Kisses»."},
  {"id":293,"slug":"lesbian-strapon","title":"Lesbian Strapon","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Lesbian Strapon»."},
  {"id":294,"slug":"lesbian-tongue-kissing","title":"Lesbian Tongue Kissing","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Lesbian Tongue Kissing»."},
  {"id":295,"slug":"lips-and-tongue","title":"Lips & Tongues","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Lips & Tongues»."},
  {"id":296,"slug":"lips-that-grip","title":"Lips That Grip","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Lips That Grip»."},
  {"id":297,"slug":"lm-xf-latin-male-any-female","title":"LM/XF (Latin Male, Any Female)","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «LM/XF (Latin Male, Any Female)»."},
  {"id":298,"slug":"long-legged-shorties","title":"Long Legged Shorties","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Long Legged Shorties»."},
  {"id":299,"slug":"long-nail-fetish","title":"Long Nail Fetish","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Long Nail Fetish»."},
  {"id":300,"slug":"long-sexy-legs","title":"Long Sexy Legs","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Long Sexy Legs»."},
  {"id":301,"slug":"make-daddy-cum","title":"Make Daddy Cum","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Make Daddy Cum»."},
  {"id":302,"slug":"male-domination","title":"Male Domination","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Male Domination»."},
  {"id":303,"slug":"masked","title":"Masked","category":"cosplay","description":"Воспроизводимый cosplay/образ или тематический roleplay «Masked»."},
  {"id":304,"slug":"massage-porn","title":"Massage Porn","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Massage Porn»."},
  {"id":305,"slug":"masturbation","title":"Masturbation","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Masturbation»."},
  {"id":306,"slug":"mating-press","title":"Mating Press","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Mating Press»."},
  {"id":307,"slug":"mature-and-naughty","title":"Mature & Naughty","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Mature & Naughty»."},
  {"id":308,"slug":"mature-shemales","title":"Mature Shemales","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Mature Shemales»."},
  {"id":309,"slug":"mature-over-50","title":"Mature: Over 50","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Mature: Over 50»."},
  {"id":310,"slug":"mean-girls","title":"Mean Girls","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Mean Girls»."},
  {"id":311,"slug":"metal-bondage","title":"Metal Bondage","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Metal Bondage»."},
  {"id":312,"slug":"mexican-girls","title":"Mexican Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Mexican Girls»."},
  {"id":313,"slug":"microchastity","title":"Microchastity","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Microchastity»."},
  {"id":314,"slug":"middle-aged-boobs","title":"Middle Aged Boobs","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Middle Aged Boobs»."},
  {"id":315,"slug":"milfs-over-30","title":"MILFs Over 30","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «MILFs Over 30»."},
  {"id":316,"slug":"misogyny","title":"Misogyny Roleplay","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Misogyny Roleplay»."},
  {"id":317,"slug":"missionary-anal","title":"Missionary Anal","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Missionary Anal»."},
  {"id":318,"slug":"missionary-soles","title":"Missionary Soles","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Missionary Soles»."},
  {"id":319,"slug":"mmf","title":"MMF","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «MMF»."},
  {"id":320,"slug":"money-shots","title":"Money Shots","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Money Shots»."},
  {"id":321,"slug":"mouth-kink","title":"Mouth Kink","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Mouth Kink»."},
  {"id":322,"slug":"multiracial","title":"Multiracial","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Multiracial»."},
  {"id":323,"slug":"nail-fetish","title":"Nail fetish","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Nail fetish»."},
  {"id":324,"slug":"natural-big-tits","title":"Natural Big Tits","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Natural Big Tits»."},
  {"id":325,"slug":"naughty-asians","title":"Naughty Asians","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Naughty Asians»."},
  {"id":326,"slug":"new-york-girls","title":"NEW YORK GIRLS ✨","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «NEW YORK GIRLS ✨»."},
  {"id":327,"slug":"new-york-nine","title":"New York Nines","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «New York Nines»."},
  {"id":328,"slug":"not-your-everyday-sex-positions","title":"Not Your Everyday Sex Positions","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Not Your Everyday Sex Positions»."},
  {"id":329,"slug":"nothing-underneath","title":"Nothing Underneath","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Nothing Underneath»."},
  {"id":330,"slug":"nsfw-cosplay","title":"NSFW Cosplay","category":"cosplay","description":"Воспроизводимый cosplay/образ или тематический roleplay «NSFW Cosplay»."},
  {"id":331,"slug":"nurse","title":"Nurses","category":"cosplay","description":"Воспроизводимый cosplay/образ или тематический roleplay «Nurses»."},
  {"id":332,"slug":"oil-porn","title":"Oiled","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Oiled»."},
  {"id":333,"slug":"old-v-young","title":"Old v Young","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Old v Young»."},
  {"id":334,"slug":"old-young-lesbians","title":"Old/Young Lesbians","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Old/Young Lesbians»."},
  {"id":335,"slug":"on-all-fours","title":"On All Fours","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «On All Fours»."},
  {"id":336,"slug":"on-her-knees","title":"On Her Knees","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «On Her Knees»."},
  {"id":337,"slug":"on-off","title":"On/Off","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «On/Off»."},
  {"id":338,"slug":"orgasmic-contractions","title":"Orgasmic Contractions","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Orgasmic Contractions»."},
  {"id":339,"slug":"outercourse","title":"Outercourse","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Outercourse»."},
  {"id":340,"slug":"over-40","title":"Over 40","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Over 40»."},
  {"id":341,"slug":"paag","title":"PAAG","category":"appearance","description":"PAAG — model-type ниша; официальное описание RedGIFs отсутствует, поэтому точная расшифровка по metadata не подтверждена."},
  {"id":342,"slug":"painted-succubus","title":"Painted Succubus","category":"cosplay","description":"Воспроизводимый cosplay/образ или тематический roleplay «Painted Succubus»."},
  {"id":343,"slug":"pale-girls","title":"Pale Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Pale Girls»."},
  {"id":344,"slug":"pale-nipples","title":"Pale Nipples","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Pale Nipples»."},
  {"id":345,"slug":"peeing","title":"Peeing","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Peeing»."},
  {"id":346,"slug":"pegging-gangbang","title":"Pegging GangBang","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Pegging GangBang»."},
  {"id":347,"slug":"pegging-pov","title":"Pegging POV","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Pegging POV»."},
  {"id":348,"slug":"perfect-body","title":"Perfect Body","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Perfect Body»."},
  {"id":349,"slug":"petite-chicks","title":"Petite Chicks","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Petite Chicks»."},
  {"id":350,"slug":"phat-ass-white-girls","title":"Phat Ass White Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Phat Ass White Girls»."},
  {"id":351,"slug":"phone-cheating","title":"Phone Cheating","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Phone Cheating»."},
  {"id":352,"slug":"pillow-humping-joi","title":"Pillow Humping JOI","category":"performance","description":"Формат подачи, речь/звук или performance-приём «Pillow Humping JOI»."},
  {"id":353,"slug":"piss-pov","title":"Piss POV","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Piss POV»."},
  {"id":354,"slug":"piss-sluts","title":"Piss Sluts","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Piss Sluts»."},
  {"id":355,"slug":"playful","title":"Playful","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Playful»."},
  {"id":356,"slug":"plow-fucking","title":"Plow Fucking","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Plow Fucking»."},
  {"id":357,"slug":"plugged","title":"Plugged","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Plugged»."},
  {"id":358,"slug":"pregnant-porn","title":"Pregnant Porn","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Pregnant Porn»."},
  {"id":359,"slug":"prejac-training","title":"Prejac Training","category":"performance","description":"Формат подачи, речь/звук или performance-приём «Prejac Training»."},
  {"id":360,"slug":"prone-boning","title":"Prone Boning","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Prone Boning»."},
  {"id":361,"slug":"puffies","title":"Puffies","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Puffies»."},
  {"id":362,"slug":"pulsating-assholes","title":"Pulsating Assholes","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Pulsating Assholes»."},
  {"id":363,"slug":"pup-community","title":"Pup Community","category":"roleplay","description":"Постановочный сценарий, персона или партнёрская динамика «Pup Community»."},
  {"id":364,"slug":"pussy-from-behind","title":"Pussy From Behind","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Pussy From Behind»."},
  {"id":365,"slug":"pussy-frosting","title":"Pussy Frosting","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Pussy Frosting»."},
  {"id":366,"slug":"pussy-grool","title":"Pussy Grool","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Pussy Grool»."},
  {"id":367,"slug":"pussy-spreading","title":"Pussy Spreading","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Pussy Spreading»."},
  {"id":368,"slug":"pussy-wedgie","title":"Pussy Wedgie","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Pussy Wedgie»."},
  {"id":369,"slug":"queefing","title":"Queefing","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Queefing»."},
  {"id":370,"slug":"queen-of-hearts","title":"Queen of Hearts","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Queen of Hearts»."},
  {"id":371,"slug":"real-bdsm","title":"Real BDSM","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Real BDSM»."},
  {"id":372,"slug":"real-couples","title":"Real Couples","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Real Couples»."},
  {"id":373,"slug":"real-orgasms","title":"Real Orgasms","category":"action","description":"Реалистичные/натуральные оргазмические реакции. Официальное описание RedGIFs отсутствует."},
  {"id":374,"slug":"real-outdoor-enjoyers","title":"Real Outdoor Enjoyers","category":"location","description":"Съёмочная ситуация или локационный концепт «Real Outdoor Enjoyers»."},
  {"id":375,"slug":"real-tease","title":"Real Tease","category":"performance","description":"Формат подачи, речь/звук или performance-приём «Real Tease»."},
  {"id":376,"slug":"real-work-sexy-angles","title":"Real Work, Sexy Angles","category":"location","description":"Съёмочная ситуация или локационный концепт «Real Work, Sexy Angles»."},
  {"id":377,"slug":"redheads","title":"Redheads","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Redheads»."},
  {"id":378,"slug":"retrousse-tits-upward-pointing-tits","title":"Retrousse Tits (Upward pointing Tits)","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Retrousse Tits (Upward pointing Tits)»."},
  {"id":379,"slug":"riding-dick","title":"Riding Dick","category":"action","description":"Сцены riding/cowgirl, где женщина находится сверху. Официальное описание RedGIFs отсутствует."},
  {"id":380,"slug":"ripped-clothing","title":"Ripped Clothing","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Ripped Clothing»."},
  {"id":381,"slug":"rolling-eyes","title":"Rolling eyes","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Rolling eyes»."},
  {"id":382,"slug":"romantic-sex","title":"Romantic Sex","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Romantic Sex»."},
  {"id":383,"slug":"rough-sex","title":"Rough Sex","category":"action","description":"Жёсткая партнёрская секс-сцена; использовать только как consensual постановку. Официальное описание RedGIFs отсутствует."},
  {"id":384,"slug":"ruined-orgasms","title":"Ruined Orgasms","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Ruined Orgasms»."},
  {"id":385,"slug":"self-titty-suck","title":"Self Titty Suck","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Self Titty Suck»."},
  {"id":386,"slug":"selfies","title":"Selfies","category":"performance","description":"Формат подачи, речь/звук или performance-приём «Selfies»."},
  {"id":387,"slug":"sensualsloppy","title":"Sensual Sloppy","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Sensual Sloppy»."},
  {"id":388,"slug":"dildos","title":"Sex Toys","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Sex Toys»."},
  {"id":389,"slug":"sexy-exhibition","title":"Sexy Exhibition","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Sexy Exhibition»."},
  {"id":390,"slug":"sexy-eyes","title":"Sexy Eyes","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Sexy Eyes»."},
  {"id":391,"slug":"sexy-frex","title":"Sexy Frex","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Sexy Frex»."},
  {"id":392,"slug":"sexy-lingerie","title":"Sexy Lingerie","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Sexy Lingerie»."},
  {"id":393,"slug":"shaved-pussies","title":"Shaved Pussies","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Shaved Pussies»."},
  {"id":394,"slug":"she-fucks-him","title":"She Fucks Him","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «She Fucks Him»."},
  {"id":395,"slug":"shiny","title":"Shiny","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Shiny»."},
  {"id":396,"slug":"shiny-clothes","title":"Shiny Clothes","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Shiny Clothes»."},
  {"id":397,"slug":"short-girls","title":"Short Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Short Girls»."},
  {"id":398,"slug":"short-hair-chicks","title":"Short Hair Chicks","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Short Hair Chicks»."},
  {"id":399,"slug":"short-shorts","title":"Short Shorts","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Short Shorts»."},
  {"id":400,"slug":"sidewinders","title":"Sidewinders","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Sidewinders»."},
  {"id":401,"slug":"silicone-fantasy","title":"Silicone Fantasy","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Silicone Fantasy»."},
  {"id":402,"slug":"sit-on-my-camera","title":"Sit On My Camera","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Sit On My Camera»."},
  {"id":403,"slug":"sixty-nine","title":"Sixty Nine","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Sixty Nine»."},
  {"id":404,"slug":"size-queen","title":"Size Queen","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Size Queen»."},
  {"id":405,"slug":"skater-skirts","title":"Skater Skirts","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Skater Skirts»."},
  {"id":406,"slug":"slim-thick-baddies","title":"Slim thick baddies","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Slim thick baddies»."},
  {"id":407,"slug":"sloppy-lesbian-kissing","title":"Sloppy Lesbian Kissing","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Sloppy Lesbian Kissing»."},
  {"id":408,"slug":"sloppy-seconds","title":"Sloppy Seconds","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Sloppy Seconds»."},
  {"id":409,"slug":"sluty-milfs","title":"Slutty MILFs","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Slutty MILFs»."},
  {"id":410,"slug":"sneaky-porn","title":"Sneaky Porn","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Sneaky Porn»."},
  {"id":411,"slug":"solo","title":"Solo","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Solo»."},
  {"id":412,"slug":"spit-in-mouth","title":"Spit In Mouth","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Spit In Mouth»."},
  {"id":413,"slug":"spitroasted","title":"Spitroasted","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Spitroasted»."},
  {"id":414,"slug":"squealing-babes","title":"Squealing Babes","category":"action","description":"По названию — акцент на громких женских вокальных реакциях; официальное описание RedGIFs отсутствует."},
  {"id":415,"slug":"squirters","title":"Squirters","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Squirters»."},
  {"id":416,"slug":"squirting-camgirls","title":"Squirting Camgirls","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Squirting Camgirls»."},
  {"id":417,"slug":"squirting-lesbians","title":"Squirting Lesbians","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Squirting Lesbians»."},
  {"id":418,"slug":"st-louis-creators","title":"St.Louis Creators","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «St.Louis Creators»."},
  {"id":419,"slug":"streamer-girls","title":"Streamer Girls","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Streamer Girls»."},
  {"id":420,"slug":"supine-blowjobs","title":"Supine Blowjobs","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Supine Blowjobs»."},
  {"id":421,"slug":"swallow","title":"Swallow","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Swallow»."},
  {"id":422,"slug":"swingers","title":"Swingers","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Swingers»."},
  {"id":423,"slug":"tag-team","title":"Tag Team","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Tag Team»."},
  {"id":424,"slug":"thick-booty","title":"Thick Booty","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Thick Booty»."},
  {"id":425,"slug":"thick-fit","title":"Thick Fit","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Thick Fit»."},
  {"id":426,"slug":"t-h-i-c-k-t-h-i-g-h-s","title":"Thick Thighs","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Thick Thighs»."},
  {"id":427,"slug":"thigh-fucking","title":"Thigh Fucking","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Thigh Fucking»."},
  {"id":428,"slug":"dat-gap","title":"Thigh Gap","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Thigh Gap»."},
  {"id":429,"slug":"thigh-socks","title":"Thigh Socks","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Thigh Socks»."},
  {"id":430,"slug":"thongs","title":"Thongs","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Thongs»."},
  {"id":431,"slug":"throatfucking","title":"Throat Fucking","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Throat Fucking»."},
  {"id":432,"slug":"throated","title":"Throated","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Throated»."},
  {"id":433,"slug":"throatpies","title":"Throatpies","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Throatpies»."},
  {"id":434,"slug":"tickling","title":"Tickling","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Tickling»."},
  {"id":435,"slug":"tight-assholes","title":"Tight Assholes","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Tight Assholes»."},
  {"id":436,"slug":"tight-leggings","title":"Tight leggings","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Tight leggings»."},
  {"id":437,"slug":"tight-skirts-and-dresses","title":"Tight Skirts & Dresses","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Tight Skirts & Dresses»."},
  {"id":438,"slug":"tik-tok","title":"Tik Tok","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Tik Tok»."},
  {"id":439,"slug":"tiktok-hips","title":"TikTok Hips","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «TikTok Hips»."},
  {"id":440,"slug":"tiny-tits","title":"Tiny Tits","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Tiny Tits»."},
  {"id":441,"slug":"tit-worship","title":"Tit Worship","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Tit Worship»."},
  {"id":442,"slug":"titty-flexing","title":"Titty Flexing","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Titty Flexing»."},
  {"id":443,"slug":"titty-drop","title":"TittyDrop","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «TittyDrop»."},
  {"id":444,"slug":"tittyfucking","title":"Tittyfucking","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Tittyfucking»."},
  {"id":445,"slug":"tongue-job","title":"Tongue Job","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Tongue Job»."},
  {"id":446,"slug":"toyjobs","title":"Toyjobs","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Toyjobs»."},
  {"id":447,"slug":"trans-babes-getting-a-blowjob","title":"Trans Babes Getting A Blowjob","category":"appearance","description":"Trans-women, получающие оральный секс; официальное описание RedGIFs отсутствует."},
  {"id":448,"slug":"trans-cumshots","title":"Trans Cumshots","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Trans Cumshots»."},
  {"id":449,"slug":"trans-fucks-guy","title":"Trans Fucks Guy","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Trans Fucks Guy»."},
  {"id":450,"slug":"trans-fucks-trans","title":"Trans Fucks Trans","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Trans Fucks Trans»."},
  {"id":451,"slug":"trans-selfcum","title":"Trans Selfcum","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Trans Selfcum»."},
  {"id":452,"slug":"trans-women","title":"Trans Women","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Trans Women»."},
  {"id":453,"slug":"transparent-clothing","title":"Transparent Clothing","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Transparent Clothing»."},
  {"id":454,"slug":"twerk","title":"Twerk","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Twerk»."},
  {"id":455,"slug":"uk-girls","title":"UK Girls","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «UK Girls»."},
  {"id":456,"slug":"ukrainian-slut","title":"Ukrainian Sluts","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Ukrainian Sluts»."},
  {"id":457,"slug":"underneath","title":"Underneath","category":"camera","description":"Референсы на конкретную позу, композицию или ракурс «Underneath»."},
  {"id":458,"slug":"undies","title":"Undies","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Undies»."},
  {"id":459,"slug":"unsheathing-toys","title":"Unsheathing Toys","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Unsheathing Toys»."},
  {"id":460,"slug":"up-close-pussy","title":"Up-Close Pussy","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Up-Close Pussy»."},
  {"id":461,"slug":"upskirt-tease","title":"Upskirt Tease","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Upskirt Tease»."},
  {"id":462,"slug":"vacuum-pumping","title":"Vacuum Pumping","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «Vacuum Pumping»."},
  {"id":463,"slug":"voluptuous-bbw","title":"Voluptuous BBW","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Voluptuous BBW»."},
  {"id":464,"slug":"wearing-stockings","title":"Wearing Stockings","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Wearing Stockings»."},
  {"id":465,"slug":"wheelchair-baddies-women-only","title":"Wheelchair Baddies (Women Only)","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Wheelchair Baddies (Women Only)»."},
  {"id":466,"slug":"when-it-goes-in","title":"When It Goes In","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «When It Goes In»."},
  {"id":467,"slug":"women-in-uniform","title":"Women in Uniform","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «Women in Uniform»."},
  {"id":468,"slug":"women-of-color","title":"Women Of Color","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Women Of Color»."},
  {"id":469,"slug":"women-with-tanlines","title":"Women with Tanlines","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Women with Tanlines»."},
  {"id":470,"slug":"xtreme-gussets","title":"XTREME GUSSETS","category":"outfit","description":"Контент, где ключевой визуальный элемент образа — «XTREME GUSSETS»."},
  {"id":471,"slug":"you-re-so-big","title":"You're So Big","category":"action","description":"Конкретное действие, фетиш, поза или партнёрская сцена «You're So Big»."},
  {"id":472,"slug":"young-milf","title":"Young MILFs","category":"appearance","description":"Ниша для matching по внешности, телосложению, идентичности или типажу «Young MILFs»."},
  {"id":473,"slug":"zelda-cosplays","title":"Zelda Cosplays","category":"cosplay","description":"Воспроизводимый cosplay/образ или тематический roleplay «Zelda Cosplays»."},
]);

const BY_SLUG = new Map(REFERENCE_CATALOG.map((item) => [item.slug, item]));
const BY_ID = new Map(REFERENCE_CATALOG.map((item) => [item.id, item]));

export function isReferenceCatalogSlug(value: string): boolean {
  return BY_SLUG.has(value);
}

export function referenceCatalogBySlug(slug: string): ReferenceCatalogEntry | undefined {
  return BY_SLUG.get(slug);
}

export function referenceCatalogById(id: number): ReferenceCatalogEntry | undefined {
  return BY_ID.get(id);
}

export function referenceCategoryItems(category: string): ReferenceCatalogEntry[] {
  return REFERENCE_CATALOG.filter((item) => item.category === category);
}
