name = "instagram-creative-bot"
main = "src/index.ts"
compatibility_date = "2026-08-05"
workers_dev = true

# GitHub Actions automatically creates this KV namespace and replaces the placeholder.
[[kv_namespaces]]
binding = "CONFIG"
id = "__KV_NAMESPACE_ID__"

[vars]
GITHUB_REF = "main"
GITHUB_WORKFLOW = "process-instagram.yml"
GITHUB_OWNER = "__GITHUB_OWNER__"
GITHUB_REPO = "__GITHUB_REPO__"
